#!/usr/bin/env bash
#
# Run a command, via local directories first, then the environment/PATH.
# shellcheck disable=SC2145,SC1090

set -e

################################################################################
# Run a command, via local directories first, then the environment/PATH.
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [] $args  Command to execute.
# Returns:
#   None
################################################################################
run() {
  local id="${1:-}"
  if [[ -n "${id}" ]]; then
    # Try to execute local scripts first.
    if [[ -x "./${id}" ]]; then
      "./$@"
    elif [[ -x "./bin/${id}" ]]; then
      "./bin/$@"
    elif [[ -x "./scripts/${id}" ]]; then
      "./scripts/$@"
    elif [[ -r "./scripts/${id}.sh" ]]; then
      . "./scripts/${id}.sh"
      "$@"
    elif [[ -x "./scripts/functions/${id}" ]]; then
      "./scripts/functions/$@"
    elif [[ -r "./scripts/functions/${id}.sh" ]]; then
      . "./scripts/functions/${id}.sh"
      "$@"
    else
      # Or pass it to the command line.
      "$@"
    fi
  fi
}

run "$@"
